---
title: "About Item Response Theory"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Background on Item Response Theory, the 1-Parameter Logistic Model, and the PNT-CAT

The adaptive testing algorithm and the scoring metric for all versions of the PNT included in this application are based on a 1-parameter logistic item response theory (1-PL IRT) model of the PNT [(Fergadiotis et al., 2015)](https://pubs.asha.org/doi/full/10.1044/2015_JSLHR-L-14-0249?casa_token=dPjWhuIEXvIAAAAA%3AOw0hz7jHSJ8DQ_yMJktmknbwqzGnUXYWSrwL6eU75qbOu3SjXdkst4JjD19oMrtDNhbC-glwJV6dQWI). An IRT model places items and persons on a common latent trait scale and, given calibrated estimates of item difficulty and person ability, provides predictions for the expected response to each item by each person. Alternatively, given a set of item difficulty estimates and a string of associated responses from an individual, the 1-PL IRT model provides a score estimate and an associated standard error of measurement. Following the convention of the IRT literature, the item difficulty and person ability estimates in this application have been scaled such that when they are equal, the expected response is 0.5, meaning that if 100 individuals with ability = 50 are administered an item of difficulty = 50, there will be approximately 50 correct and 50 incorrect responses. Likewise, if a person with ability = 50 is given 100 items all with difficulty = 50, they will be expected to respond correctly to half. As person ability increases relative to item difficulty, the expected score increases above 0.5, and as person ability decreases relative to item difficulty, the expected score decreases below 0.5, reaching an asymptote as the expectation approaches 0 or 1.

- Interested readers are referred to [Baylor and colleagues (2011)]((https://pubs.asha.org/doi/abs/10.1044/1058-0360%282011/10-0079%29?rfr_dat=cr_pub++0pubmed&url_ver=Z39.88-2003&rfr_id=ori%3Arid%3Acrossref.org)) for a general introduction to item response theory for speech-language pathologists
- Alex Swiderski’s [Shiny Application](https://aswiderski.shinyapps.io/ShinyIRT/) provides a graphical presentation of the 1-PL IRT model for the PNT and some key concepts in IRT. 
- See [Fergadiotis, Casilio, Hula, and Swiderski (2021)](https://pubmed.ncbi.nlm.nih.gov/34261162/) for an overview of the research program on which this PNT-CAT testing application is based. 
- Initial fitting and evaluation of the 1-PL model to the PNT in a frequentest statistical framework was reported by [Fergadiotis, Kellough, and Hula (2015)](https://pubs.asha.org/doi/full/10.1044/2015_JSLHR-L-14-0249?casa_token=dPjWhuIEXvIAAAAA%3AOw0hz7jHSJ8DQ_yMJktmknbwqzGnUXYWSrwL6eU75qbOu3SjXdkst4JjD19oMrtDNhbC-glwJV6dQWI), using a sample of 251 persons with aphasia from the Moss Aphasia Psycholinguistics Project Database ([MAPPD; Mirman et al., 2010](https://www.tandfonline.com/doi/abs/10.1080/02643294.2011.574112)).
- Initial development and simulation testing of the PNT-CAT versions using the same data set  from the MAPPD was reported in [Hula, Kellough, & Fergadiotis (2015)](https://pubs.asha.org/doi/full/10.1044/2015_JSLHR-L-14-0297?casa_token=tMSqOL5JpXkAAAAA%3AXPYov-zlx9fluRZwBRhsOuzkWzM20RyVuQ3US3M4TZqekdpq1njZ2pLqjzQ0PBDHhpPSEssU8RYmAHQ). 
- Empirical comparison of the PNT-CAT30 to the full PNT was reported in Fergadiotis, Hula, [Swiderski, Lei, and Kellough (2019)](https://pubs.asha.org/doi/abs/10.1044/2018_JSLHR-L-18-0344).
- Empirical comparison of the PNT-CAT30 and PNT-CATVL was described in [Hula, Fergadiotis, Swiderski, Silkes, & Kellough (2020)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7213484/). 
- A refitting of the PNT to the 1-PL model in a Bayesian statistical framework, based on larger data set from the MAPPD was reported by Huston (2021), and the current item difficulty estimates are taken from this work. 

