---
title: "PNT Versions"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### PNT-CAT30: 30-item Computer Adaptive Version

This version adaptively administers 30 items, beginning with an item of average difficulty. Items are selected to provide the maximum reduction in the standard error of measurement at the current ability estimate based on the responses collected thus far. Score estimates from the PNT-CAT30 correlated 0.95 with scores from the full PNT [(Fergadiotis et al., 2019)](https://www.tandfonline.com/doi/abs/10.1080/02687038.2018.1495310), were not reliably different, and are suitable for estimating the overall severity of anomia in persons with aphasia due to left hemisphere stroke. The PNT-CAT30 requires an average of 8-9 minutes to administer, with approximately 75% of respondents from [Fergadiotis et al. (2019)](https://www.tandfonline.com/doi/abs/10.1080/02687038.2018.1495310) completing the test in 10 minutes or less, including instructions and practice items.

### PNT-CATVL: Variable-length Computer Adaptive Alternate Form

This version adaptively administers items until the standard error of the score estimate is as precise as it was for a previously administered PNT-CAT30. It also excludes the items given in the previous PNT-CAT30. Administering this version requires upload of spreadsheet output from the previous administration. Score estimates from the PNT-CATVL correlated 0.89 with independent estimates from the PNT-CAT30 [(Hula et al., 2020)](https://pubs.asha.org/doi/abs/10.1044/2019_JSLHR-L-19-0213) and were not reliably different. The PNT-CATVL administers up to 100 items, the median number of items administered by [Hula et al. (2020)](https://pubs.asha.org/doi/abs/10.1044/2019_JSLHR-L-19-0213) was 43.5 and the minimum number was 21. The average administration time was 9-10 minutes, with 75% of participants completing the test in 14 minutes or less. The maximum administration time was 20 minutes.

### PNT-30A, PNT-30B: 30-item static short forms A  & B [(Walker & Schwartz, 2012)](https://pubs.asha.org/doi/abs/10.1044/1058-0360%282012/11-0089%29)

These are two static (i.e., fixed) 30-item PNT short forms with non-overlapping item content developed by Walker and Schwartz to reproduce the psychometric properties of the full PNT and each other. Accuracy scores on the PNT-30A and PNT-30B were not significantly different and the two short forms correlated highly with each other (0.93), and with the full PNT (0.93 and 0.98), respectively. Accuracy in terms of percent correct was significantly higher on the short forms than on the full PNT. [Walker and Schwartz (2012)](https://pubs.asha.org/doi/abs/10.1044/1058-0360%282012/11-0089%29) provide a table to convert number correct scores on each form to an equivalent percent correct score on the full PNT. The IRT-based scoring metric in this application automatically provides T-score estimates for these short forms that are on the same scale as the other test versions. Thus there is no need to correct for differences in average accuracy between the PNT-30A and B short forms and the full PNT when using this application. Although Walker and Schwartz did not report administration times for these short forms, they can be expected to be similar to those reported above for the PNT-CAT30.

### PNT-CAT175: Full 175-item version in adaptive order

This selection provides administration of all 175 items in adaptive order, beginning with an item that targets the average ability in the calibration sample and proceeding as described above for the PNT-CAT30. In the sample of persons with aphasia reported by Fergadiotis et al. (2019), the mean (SD) administration time for the full PNT was 31 (11.7) minutes. The minimum and maximum administration times were 11 and 60 minutes, respectively, and 75% of participants completed the test in 39 minutes or less. This version of the test should be used when a maximally precise score estimate is required, e.g., when trying to measure the general effects of treatment for an individual in the chronic phase of recovery. Of note, a clinician user can stop this version of the test at any point during administration and download an output file containing a record of the items, responses, and score estimates up to that point. The final score estimate and standard error can be interpreted and used like any other provided by the application, and provided that at least 30 items were administered, it should have favorable psychometric properties similar to or better than those reported for the PNT-CAT30.

### PNT-175: Full 175-item version in standard administration order

This option provides administration of all 175 items in standard PNT administration order. Although this test can also be stopped at any point during administration and will provide a theoretically valid score estimate and standard error, this is not recommended because we have not collected evidence regarding the validity of short form score estimates obtained in this way.
