---
title: "References"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Baylor, C., Hula, W. D., Donovan, N. J., Doyle, P. J., Kendall, D., & Yorkston, K. (2011). An introduction to item response theory and Rasch models for speech-language pathologists. American Journal of Speech-Language Pathology, 20(3), 243–259.

Fergadiotis, G., Casilio, M., Hula, W. D., & Swiderski, A. M. (2021). Computer adaptive testing for the assessment of anomia severity. Seminars in Speech and Language.

Fergadiotis, G., Hula, W. D., Swiderski, A. M., Lei, C.-M., & Kellough, S. (2019). Enhancing the efficiency of confrontation naming assessment for aphasia using computer adaptive testing. Journal of Speech, Language, and Hearing Research, 62(6), 1724–1738.

Fergadiotis, G., Kellough, S., & Hula, W. D. (2015). Item response theory modeling of the Philadelphia Naming Test. Journal of Speech, Language, and Hearing Research, 58(3), 865–877.

Hula, W. D., Fergadiotis, G., Swiderski, A. M., Silkes, J. P., & Kellough, S. (2020). Empirical Evaluation of Computer-Adaptive Alternate Short Forms for the Assessment of Anomia Severity. Journal of Speech, Language, and Hearing Research, 63(1), 163–172.

Hula, W. D., Kellough, S., & Fergadiotis, G. (2015). Development and simulation testing of a computerized adaptive version of the Philadelphia naming test. Journal of Speech, Language, and Hearing Research, 1–13. https://doi.org/10.1044/2015_JSLHR-L-14-0297

Huston, H. (2021). Bayesian item response theory modelling [Maser’s thesis]. Portland State University.

Kaplan, E., Goodlgass, H., & Weintraub, S. (2001). Boston Naming Test (2nd ed.). Lippincott Williams & Wilkins.

Mirman, D., Strauss, T. J., Brecher, A., Walker, G. M., Sobel, P., Dell, G. S., & Schwartz, M. F. (2010). A large, searchable, web-based database of aphasic performance on picture naming and other tests of cognitive function. Cognitive Neuropsychology, 27(6), 495–504.

Walker, G. M., Hickok, G., & Fridriksson, J. (2018). A cognitive psychometric model for assessment of picture naming abilities in aphasia. Psychological Assessment, 809–826.

Walker, G. M., & Schwartz, M. F. (2012). Short-Form Philadelphia Naming Test: Rationale and Empirical Evaluation. American Journal of Speech-Language Pathology, 21(2), S140–S153.

